name: Pull Request Notification

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Display PR info
        run: echo "A new Pull Request has been opened."